name: publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  PLATFORM: "linux/amd64,linux/arm64"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
          
      - name: Build the Docker image
        run: |
          docker buildx create --name=qemu
          docker buildx use qemu
          docker buildx build --pull --platform=$(env.PLATFORM) --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --push .
